name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  'test':
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Test on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test --silent --ci --reporters=default --reporters=jest-github-actions-reporter --coverage --coverageReporters=text --coverageReporters=text-summary
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: all
          coverage-file: coverage/report.json
